services:
  grafana:
    user: root
    container_name: 'mayankkholia1-timechartwithversion-panel'

    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.3.1}
        development: ${DEVELOPMENT:-false}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/mayankkholia1-timechartwithversion-panel
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/mayankkholia1-timechartwithversion-panel

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.mayankkholia1-timechartwithversion-panel:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: mayankkholia1-timechartwithversion-panel
  prometheus:
    user: root
    container_name: "prometheus-server"
    image: prom/prometheus
    ports:
      - 9090:9090/tcp
    volumes:
      - extra/prometheus.yml:/etc/prometheus/prometheus.yml
    
  pushgateway:
    user: root
    container_name: "pushgateway"
    image: prom/pushgateway
    ports:
      - 9091:9091/tcp