services:
  grafana:
    user: root
    container_name: 'someone-timechartwithversion-panel'

    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.3.1}
        development: ${DEVELOPMENT:-false}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/someone-timechartwithversion-panel
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/someone-timechartwithversion-panel

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.someone-timechartwithversion-panel:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: someone-timechartwithversion-panel
